name: Run Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Run Tests
        run: zig build test
